# Generated by Django 5.0 on 2024-02-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=20)),
                ('catch_copy', models.CharField(default='', max_length=30)),
                ('explanation', models.CharField(default='', max_length=200)),
                ('price_min', models.PositiveIntegerField(default='0')),
                ('price_max', models.PositiveIntegerField(default='0')),
                ('address', models.CharField(default='', max_length=200)),
                ('tel', models.CharField(default='', max_length=11)),
                ('open_time', models.CharField(default='', max_length=5)),
                ('close_time', models.TimeField(default='')),
                ('close_day', models.TimeField(default='')),
                ('img', models.ImageField(blank=True, default='img/noImage.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('password1', models.CharField(default='', max_length=20)),
                ('password2', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
