# Generated by Django 5.0 on 2024-02-26 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='店舗名')),
                ('price_max', models.PositiveIntegerField(default='0', verbose_name='価格（最大）')),
                ('price_min', models.PositiveIntegerField(default='0', verbose_name='価格（最小）')),
                ('seat', models.PositiveIntegerField(default='0', verbose_name='座席数')),
                ('address', models.CharField(default='', max_length=200, verbose_name='住所')),
                ('tel', models.CharField(default='', max_length=11, verbose_name='電話番号')),
                ('open_time', models.TimeField(default='', verbose_name='営業時間(開始)')),
                ('close_time', models.TimeField(default='', verbose_name='営業時間(終了)')),
                ('close_day', models.CharField(default='', max_length=20, verbose_name='定休日')),
                ('catch_copy', models.CharField(default='', max_length=30, verbose_name='キャッチコピー')),
                ('explanation', models.TextField(default='', max_length=300, verbose_name='説明')),
                ('img', models.ImageField(blank=True, default='img/noImage.png', upload_to='', verbose_name='店舗画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NagoyameshiApp.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, verbose_name='氏名')),
                ('furigana', models.CharField(default='', max_length=50, verbose_name='フリガナ')),
                ('birthday', models.DateField(default='', verbose_name='生年月日')),
                ('zipcode', models.CharField(default='', max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(default='', max_length=100, verbose_name='住所')),
                ('tel', models.CharField(default='', max_length=13, verbose_name='電話番号')),
                ('works', models.CharField(blank=True, default='', max_length=20, verbose_name='ご職業')),
                ('subscription', models.BooleanField(default='False', verbose_name='サブスク契約')),
                ('admin', models.BooleanField(default='False', verbose_name='管理者権限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
