# Generated by Django 5.0 on 2024-02-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NagoyameshiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='catch_copy',
            field=models.CharField(default='', max_length=30, verbose_name='キャッチコピー'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='', max_length=20, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_day',
            field=models.TimeField(default='', verbose_name='定休日'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(default='', verbose_name='閉店時間'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='explanation',
            field=models.CharField(default='', max_length=200, verbose_name='説明文'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, default='img/noImage.png', upload_to='', verbose_name='イメージ画像'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_time',
            field=models.CharField(default='', max_length=5, verbose_name='開店時間'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_max',
            field=models.PositiveIntegerField(default='0', verbose_name='価格（最大）'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_min',
            field=models.PositiveIntegerField(default='0', verbose_name='価格（最低）'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tel',
            field=models.CharField(default='', max_length=11, verbose_name='電話番号'),
        ),
    ]
