# Generated by Django 5.0 on 2024-03-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NagoyameshiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_persons',
            field=models.PositiveIntegerField(default='', verbose_name='人数'),
        ),
    ]
