# Generated by Django 5.0 on 2024-03-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NagoyameshiApp', '0004_alter_customuser_birthday_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=150, verbose_name='username'),
        ),
    ]
