# Generated by Django 5.0 on 2024-03-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NagoyameshiApp', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, default='img/noImage.png', upload_to='photos', verbose_name='店舗画像'),
        ),
    ]
